### ISSUE TITLE
I deployed it and it doesn't work

### ISSUE THREAD

**Issue by lmuiotctf** [KenTandrian/ai-image-generator#278]
# Cloud Functions
FIREBASE_API_KEY=
FIREBASE_AUTH_DOMAIN=
FIREBASE_PROJECT_ID=
FIREBASE_STORAGE_BUCKET=
FIREBASE_MESSAGING_SENDER_ID=3
FIREBASE_APP_ID=
FIREBASE_MEASUREMENT_ID=
FUNCTIONS_REGION=
![image](https://github.com/KenTandrian/ai-image-generator/assets/52068443/d2427e3c-efd5-4056-94e6-fd596cc6d7b2)

Why did I fill in the configuration, it can't be used here, can you give a detailed tutorial

**Comment by KenTandrian** [comment]
This application actually consists of two parts: The front-end web application (Next.js) and the back-end applications (Firebase Cloud Functions).

Did you deploy the Cloud Functions to your Firebase account?
